import './globals.css'
import { Merriweather_Sans } from 'next/font/google'

const merriwed = Merriweather_Sans({ weight: ['700'], subsets:['latin'] })

export const metadata = {
  title: 'Campaign App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={merriwed.className}>
      <main className="sm:px-[4rem] md:px-[10rem] sm:mt-4">
      {children}
      </main>
      </body>
    </html>
  )
}


export default RootLayout;